import * as tf from 'https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.22.0/+esm';
import { FilesetResolver, HandLandmarker, PoseLandmarker } from 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/+esm';

const A='/model/', SEQ=169, FEATURES=134, W=1920, H=1080;
const WASM='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm';
const HAND='https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task';
const POSE='https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task';
let labels=[], meta=null, buf=null, refs=new Map(), hand=null, pose=null, stream=null, raf=0, running=false, busy=false, seq=[];
let sentence='', stableLabel='', stableCount=0, history=JSON.parse(localStorage.getItem('mozhi-history')||'[]');
const $=s=>document.querySelector(s), esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const pretty=x=>String(x).replace(/biglarge/g,'big / large').replace(/smalllittle/g,'small / little').replace(/storeorshop/g,'store / shop').replace(/streetorroad/g,'street / road').replace(/howareyou/g,'how are you').replace(/goodafternoon/g,'good afternoon').replace(/goodevening/g,'good evening').replace(/goodmorning/g,'good morning').replace(/goodnight/g,'good night').replace(/secondnumber/g,'second / number').replace(/youplural/g,'you (plural)').replace(/raceethnicity/g,'race / ethnicity').replace(/exmonsoon/g,'monsoon');
const nav=(id,t)=>`<a class="nav-link ${location.hash.slice(1)==id?'active':''}" href="#${id}">${t}</a>`;
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}
function shell(content){app.innerHTML=`<div class="site-shell"><header class="topbar"><a class="brand" href="#home"><img src="/assets/mozhi-symbol.svg" alt="Mozhi"><span>mozhi</span></a><nav class="desktop-nav">${nav('home','Home')}${nav('translate','Translate')}${nav('learn','Learn')}${nav('history','History')}${nav('settings','Settings')}${nav('about','About')}</nav><div class="top-actions"><button class="icon-btn" id="theme">◐</button><button class="profile">V&nbsp; Vikram⌄</button><button class="icon-btn mobile-menu" id="menu">≡</button></div></header><div id="mobileNav" class="mobile-nav">${nav('home','Home')}${nav('translate','Translate')}${nav('learn','Learn')}${nav('history','History')}${nav('settings','Settings')}${nav('about','About')}</div><main>${content}</main><footer><div class="footer-brand"><img src="/assets/mozhi-symbol.svg" alt=""><div><b>mozhi</b><span>Different languages. Same humanity.</span></div></div><div class="footer-links"><a href="#translate">Translate</a><a href="#learn">Learn</a><a href="#about">About</a><a href="#settings">Settings</a></div><div class="footer-note">Deep learning • local-first • accessibility</div></footer></div>`;$('#theme').onclick=()=>document.body.classList.toggle('dark');$('#menu').onclick=()=>$('#mobileNav').classList.toggle('open')}
function loading(){app.innerHTML=`<section class="loading-screen"><img src="/assets/mozhi-wordmark.svg" alt="Mozhi"><p class="loading-tag">SIGNS BEYOND SILENCE</p><div class="loading-ring"></div><b>Loading Mozhi...</b><span>Preparing vision and deep learning</span></section>`;setTimeout(route,900)}
function home(){shell(`<section class="hero page-pad"><div class="hero-copy"><p class="eyebrow">INDIAN SIGN LANGUAGE FOR EVERY VOICE</p><h1>Signs Beyond<br>Silence.</h1><p class="hero-lede">AI-powered ISL recognition with a full temporal Transformer model. See the sign, understand the meaning, share the voice.</p><div class="hero-actions"><a class="btn primary" href="#translate">Get started →</a><a class="btn secondary" href="#about">Learn more</a></div><div class="pipeline-mini"><span>Camera</span><i>→</i><span>Landmarks</span><i>→</i><span>Transformer</span><i>→</i><span>Text</span><i>→</i><span>Voice</span></div></div><div class="hero-visual"><img class="hero-visual-image" src="/assets/hero-human.svg" alt="Hand and leaf illustration"><div class="hero-caption">HANDS SPEAK.<br>WE LISTEN.</div></div></section><section class="feature-grid page-pad"><article><span class="feature-icon">◍</span><h3>Real-time camera</h3><p>Front and rear camera capture with visible landmark tracking.</p></article><article><span class="feature-icon">◒</span><h3>Deep learning</h3><p>AI4Bharat INCLUDE Transformer inference across 263 learned classes.</p></article><article><span class="feature-icon">◓</span><h3>Text & voice</h3><p>Confirmed predictions become readable and spoken output.</p></article><article><span class="feature-icon">⌂</span><h3>Local-first</h3><p>Vision and inference run in the browser during translation.</p></article></section><section class="statement page-pad"><p class="eyebrow">THE IDEA</p><h2>Different hands.<br>Same possibility.</h2><p>Structured visual features and temporal attention turn signing into a form another person can read and hear.</p></section>`)}
function translate(){shell(`<section class="translate-page page-pad"><div class="page-intro"><div><p class="eyebrow">REAL-TIME TRANSLATION</p><h1>See the sign.<br>Understand the meaning.</h1></div><div class="status-pill" id="status"><span></span> MODEL LOADING</div></div><div class="translate-grid"><section class="camera-card"><div class="card-head"><div><p class="micro">CAMERA INPUT</p><h2>Live capture</h2></div><div class="live-badge"><span></span> LIVE</div></div><div class="camera-frame"><video id="video" autoplay playsinline muted></video><canvas id="overlay"></canvas><div class="camera-label top-left">FRONT CAMERA</div><div class="camera-label top-right" id="fps">— FPS</div><div class="scan-line"></div><div class="camera-empty" id="empty"><div class="empty-symbol"><img src="/assets/mozhi-symbol.svg" alt=""></div><b>Camera is off</b><span>Start the camera to begin recognition.</span></div><div class="camera-status"><span id="hdot"></span><span id="hstatus">Waiting for camera</span><small id="istatus">INFERENCE IDLE</small></div></div><div class="camera-controls"><button class="btn primary" id="cam">Start camera</button><button class="btn secondary" id="switch">Switch camera</button><button class="btn secondary" id="clr">Clear</button></div><div class="telemetry"><span>MODEL <b id="mstate">LOADING</b></span><span>HAND <b id="hstate">WAITING</b></span><span>INFERENCE <b id="istate">IDLE</b></span></div></section><aside class="result-column"><section class="result-card main-result"><div class="card-head"><div><p class="micro">RECOGNITION</p><h2>Detected sign</h2></div><span class="confidence" id="conf">—%</span></div><div class="prediction"><p>STABLE PREDICTION</p><strong id="pred">Waiting…</strong><span id="meaning">Start the camera and hold a sign clearly.</span></div><div class="confidence-bar"><span id="bar"></span></div></section><section class="result-card"><div class="card-head"><div><p class="micro">TEXT OUTPUT</p><h3>Your message</h3></div><button class="small-action" id="copy">Copy</button></div><div class="sentence" id="sentence">Your confirmed signs will appear here.</div><div class="result-actions"><button class="btn primary" id="speak">Speak</button><button class="btn secondary" id="undo">Undo</button></div></section><section class="tip"><b>Accuracy tip</b><span>Keep your upper body and both hands visible, use steady lighting, and hold each sign briefly.</span></section></aside></div></section>`);bind()}
function learn(){const words=['hello','thankyou','friend','good','happy','family','student','teacher','water','food','school','hospital','camera','telephone','book','beautiful','today','tomorrow','you','howareyou'];shell(`<section class="page-pad learn-page"><p class="eyebrow">LEARN ISL</p><h1>Build vocabulary<br>through practice.</h1><p class="lead">Explore common INCLUDE classes and everyday communication concepts.</p><div class="learn-grid">${words.map(w=>`<article class="learn-card"><div class="gesture-placeholder"><span>ISL</span><span class="hand-glyph">◒</span></div><div><b>${pretty(w)}</b><small>INCLUDE class</small></div><button class="round-play" data-word="${w}">▶</button></article>`).join('')}</div></section>`);document.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>speak(b.dataset.word))}
function historyPage(){shell(`<section class="page-pad history-page"><p class="eyebrow">HISTORY</p><h1>Your translations.</h1><p class="lead">Recent confirmed predictions stored locally on this device.</p><div class="history-list">${history.length?history.map((h,i)=>`<article><span class="history-num">${String(i+1).padStart(2,'0')}</span><div><b>${esc(h.label)}</b><small>${Math.round(h.confidence*100)}% • ${new Date(h.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div><button class="round-play" data-word="${esc(h.label)}">▶</button></article>`).join(''):`<div class="empty-state"><div>↺</div><b>No saved translations yet.</b><p>Start a live translation to build local history.</p></div>`}</div></section>`);document.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>speak(b.dataset.word))}
function settings(){shell(`<section class="page-pad settings-page"><p class="eyebrow">SETTINGS</p><h1>Make Mozhi yours.</h1><div class="settings-grid"><article class="settings-card"><p class="micro">OUTPUT</p><label class="setting-row"><span>Show text output</span><input type="checkbox" checked><i></i></label><label class="setting-row"><span>Enable voice output</span><input type="checkbox" checked><i></i></label><label class="setting-row"><span>Auto speak</span><input type="checkbox"><i></i></label></article><article class="settings-card"><p class="micro">VOICE</p><label class="setting-row"><span>Voice language</span><select id="locale" class="wide-setting"><option value="en-IN">English (India)</option><option value="hi-IN">Hindi</option><option value="ta-IN">Tamil</option></select></label><label class="setting-row"><span>Speech speed</span><input id="rate" class="range" type="range" min="0.7" max="1.4" step="0.1" value="1"></label></article><article class="settings-card"><p class="micro">ACCESSIBILITY</p><label class="setting-row"><span>High contrast</span><input id="hc" type="checkbox"><i></i></label><label class="setting-row"><span>Large text</span><input id="lt" type="checkbox"><i></i></label><label class="setting-row"><span>Reduced motion</span><input id="rm" type="checkbox"><i></i></label></article></div></section>`);$('#hc').onchange=e=>document.body.classList.toggle('high-contrast',e.target.checked);$('#lt').onchange=e=>document.body.classList.toggle('large-text',e.target.checked);$('#rm').onchange=e=>document.body.classList.toggle('reduce-motion',e.target.checked)}
function about(){shell(`<section class="page-pad about-page"><div class="about-hero"><div><p class="eyebrow">ABOUT MOZHI</p><h1>More than a tool.<br>A movement.</h1><p class="hero-lede">Mozhi turns Indian Sign Language into readable text and voice through real-time camera input and temporal deep learning.</p><p class="hero-lede">Built around the AI4Bharat INCLUDE research ecosystem and designed as a practical accessibility interface.</p></div><div class="about-art"><img src="/assets/hero-human.svg" alt="Mozhi inclusive hand illustration"></div></div><div class="stats"><div><b>263</b><span>INCLUDE CLASSES</span></div><div><b>169</b><span>FRAME SEQUENCE</span></div><div><b>134</b><span>FEATURES / FRAME</span></div><div><b>AI</b><span>DEEP LEARNING</span></div></div></section>`)}
function layerNorm(x, s, b){const m=tf.mean(x,-1,true),v=tf.mean(tf.square(tf.sub(x,m)),-1,true);return tf.add(tf.mul(tf.div(tf.sub(x,m),tf.sqrt(tf.add(v,1e-12))),weight(s)),weight(b))}
function weight(name){const q=refs.get(name);return tf.tensor(new Float32Array(buf,q.offset,q.length),q.shape)}
function dense(x,w,b){return tf.add(tf.matMul(x,weight(w),false,true),weight(b))}
function gelu(x){return tf.mul(.5,tf.mul(x,tf.add(1,tf.erf(tf.div(x,Math.sqrt(2))))))}
function transformerLayer(x,i){return tf.tidy(()=>{let q=dense(x,`layers.${i}.attention.self.query.weight`,`layers.${i}.attention.self.query.bias`);let k=dense(x,`layers.${i}.attention.self.key.weight`,`layers.${i}.attention.self.key.bias`);let v=dense(x,`layers.${i}.attention.self.value.weight`,`layers.${i}.attention.self.value.bias`);q=tf.transpose(tf.reshape(q,[SEQ,4,64]),[1,0,2]);k=tf.transpose(tf.reshape(k,[SEQ,4,64]),[1,0,2]);v=tf.transpose(tf.reshape(v,[SEQ,4,64]),[1,0,2]);let a=tf.softmax(tf.div(tf.matMul(q,k,false,true),8),-1);let c=tf.reshape(tf.transpose(tf.matMul(a,v),[1,0,2]),[SEQ,256]);c=dense(c,`layers.${i}.attention.output.dense.weight`,`layers.${i}.attention.output.dense.bias`);c=layerNorm(tf.add(c,x),`layers.${i}.attention.output.LayerNorm.weight`,`layers.${i}.attention.output.LayerNorm.bias`);let h=gelu(dense(c,`layers.${i}.intermediate.dense.weight`,`layers.${i}.intermediate.dense.bias`));h=dense(h,`layers.${i}.output.dense.weight`,`layers.${i}.output.dense.bias`);return layerNorm(tf.add(h,c),`layers.${i}.output.LayerNorm.weight`,`layers.${i}.output.LayerNorm.bias`)})}
function infer(sequence){return tf.tidy(()=>{let x=tf.tensor(sequence).reshape([SEQ,FEATURES]);x=dense(x,'l1.weight','l1.bias');x=layerNorm(tf.add(x,weight('embedding.position_embeddings.weight')),'embedding.LayerNorm.weight','embedding.LayerNorm.bias');x=transformerLayer(x,0);x=transformerLayer(x,1);x=tf.max(x,0);return tf.softmax(dense(x,'l2.weight','l2.bias'))})}
function feature(hs,ps){const o=[],p=ps?.landmarks?.[0]||[];for(let i=0;i<25;i++)o.push((p[i]?.x||0)*W,(p[i]?.y||0)*H);for(let h=0;h<2;h++){const lm=hs?.landmarks?.[h]||[];for(let i=0;i<21;i++)o.push((lm[i]?.x||0)*W,(lm[i]?.y||0)*H)}return o.length===FEATURES?o:null}
function draw(hs){const c=$('#overlay'),v=$('#video');if(!c||!v)return;const z=c.getContext('2d');const w=c.width=v.videoWidth||640,h=c.height=v.videoHeight||480;z.clearRect(0,0,w,h);z.strokeStyle='#75cf93';z.fillStyle='#f2efe5';z.lineWidth=2;for(const lm of hs?.landmarks||[]){for(const p of lm){z.beginPath();z.arc(p.x*w,p.y*h,3.5,0,Math.PI*2);z.fill()}}}
async function loadAssets(){const [mr,lr,br]=await Promise.all([fetch(A+'include-transformer-full.json'),fetch(A+'labels.json'),fetch(A+'include-transformer-full.bin')]);if(!mr.ok||!lr.ok||!br.ok)throw Error('model asset missing');meta=await mr.json();labels=await lr.json();buf=await br.arrayBuffer();meta.weights.forEach(q=>refs.set(q.name,q));}
async function bind(){try{await loadAssets();$('#status').classList.add('ready');$('#status').innerHTML='<span></span> MODEL READY';$('#mstate').textContent='READY';const fs=await FilesetResolver.forVisionTasks(WASM);hand=await HandLandmarker.createFromOptions(fs,{baseOptions:{modelAssetPath:HAND,delegate:'GPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.5,minHandPresenceConfidence:.5,minTrackingConfidence:.5});pose=await PoseLandmarker.createFromOptions(fs,{baseOptions:{modelAssetPath:POSE,delegate:'GPU'},runningMode:'VIDEO',numPoses:1,minPoseDetectionConfidence:.5,minPosePresenceConfidence:.5,minTrackingConfidence:.5});}catch(e){$('#mstate').textContent='ERROR';toast('Model or vision initialization failed. Check model assets.')}$('#cam').onclick=()=>running?stop():start();$('#switch').onclick=()=>toast('Use your device camera controls to switch front/rear; the next session will request the selected camera where supported.');$('#clr').onclick=()=>{sentence='';$('#sentence').textContent='Your confirmed signs will appear here.'};$('#undo').onclick=()=>{let a=sentence.split(/\s+/).filter(Boolean);a.pop();sentence=a.join(' ');$('#sentence').textContent=sentence||'Your confirmed signs will appear here.'};$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(sentence);toast('Message copied.')}catch{toast('Copy unavailable.')}};$('#speak').onclick=()=>sentence?speak(sentence):toast('No confirmed text yet.');}
async function start(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});$('#video').srcObject=stream;await $('#video').play();running=true;seq=[];$('#empty').classList.add('hidden');$('#cam').textContent='Stop camera';raf=requestAnimationFrame(loop)}catch(e){toast(e.name==='NotAllowedError'?'Camera permission denied.':'Camera unavailable.')}}
function stop(){running=false;cancelAnimationFrame(raf);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('#video').srcObject=null;$('#empty').classList.remove('hidden');$('#cam').textContent='Start camera'}
let last=0;async function loop(ts){if(!running)return;const v=$('#video');if(!v.videoWidth){raf=requestAnimationFrame(loop);return}if(ts-last>75){last=ts;try{const hs=await hand.detectForVideo(v,ts),ps=await pose.detectForVideo(v,ts);draw(hs);const f=feature(hs,ps),has=(hs.landmarks||[]).length>0;$('#hstate').textContent=has?'TRACKED':'WAITING';$('#hstatus').textContent=has?'Hand detected':'Waiting for hand';if(has&&f){seq.push(f);if(seq.length>SEQ)seq.shift();if(seq.length===SEQ&&!busy){busy=true;$('#istate').textContent='RUNNING';const p=infer(seq),a=await p.data();p.dispose();const idx=a.indexOf(Math.max(...a)),conf=a[idx]||0,label=labels[idx]||'';$('#conf').textContent=Math.round(conf*100)+'%';$('#bar').style.width=Math.round(conf*100)+'%';$('#pred').textContent=label?pretty(label):'Waiting…';$('#meaning').textContent=label?'INCLUDE class candidate':'Hold your sign clearly';if(label===stableLabel)stableCount++;else{stableLabel=label;stableCount=1}if(label&&conf>.72&&stableCount>=4){sentence=sentence?sentence+' '+pretty(label):pretty(label);$('#sentence').textContent=sentence;history.unshift({label:pretty(label),confidence:conf,time:Date.now()});history=history.slice(0,40);localStorage.setItem('mozhi-history',JSON.stringify(history));stableCount=0}$('#istate').textContent=Math.round(performance.now()-ts)+'MS';busy=false}}}catch(e){$('#istate').textContent='RECOVERY';}}raf=requestAnimationFrame(loop)}
function speak(text){if(!('speechSynthesis'in window))return toast('Speech synthesis is unavailable.');const u=new SpeechSynthesisUtterance(text);u.lang=$('#locale')?.value||'en-IN';u.rate=parseFloat($('#rate')?.value||1);speechSynthesis.cancel();speechSynthesis.speak(u)}
function route(){const r=location.hash.slice(1)||'home';({home,translate,learn,history:historyPage,settings,about}[r]||home)()}
window.addEventListener('hashchange',route);loading();
